# Generated by Django 3.1.6 on 2021-12-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attach', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('assessed', 'assessed'), ('notassessed', 'notassessed')], default='notassessed', max_length=255),
        ),
    ]
