# Generated by Django 3.1.6 on 2021-12-14 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attach', '0002_auto_20211213_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_fullname', models.CharField(max_length=255)),
                ('registration_no', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=100)),
                ('company_name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('county', models.CharField(max_length=200)),
                ('company_phone_no', models.CharField(max_length=255)),
                ('supervisor_name', models.CharField(max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='attach.studentdetails')),
            ],
        ),
    ]
