# Generated by Django 3.1.6 on 2021-12-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attach', '0003_compdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compdetails',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
