# Generated by Django 3.1.6 on 2021-12-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attach', '0004_auto_20211214_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='period_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='period_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='status',
            field=models.CharField(choices=[('assessed', 'assessed'), ('notassessed', 'notassessed')], default='notassessed', max_length=255),
        ),
    ]
